((doc,win)=>{function createTextSetter(selector){const elem=doc.querySelector(selector);let text;return newText=>{if(newText!==text){text=newText;elem.textContent=newText;return true;}
return false;};}
let set_12_24='24';doc.addEventListener('DOMContentLoaded',()=>{const setters={y:createTextSetter('#dy'),M:createTextSetter('#dm'),d:createTextSetter('#dd'),h:createTextSetter('#th'),m:createTextSetter('#tm'),s:createTextSetter('#ts'),}
const timeMask={year:doc.querySelector('#time>.mask.year>.p'),month:doc.querySelector('#time>.mask.month>.p'),d:doc.querySelector('#time>.mask.d>.p'),h:doc.querySelector('#time>.mask.h>.p'),m:doc.querySelector('#time>.mask.m>.p')};const updateText=()=>{const now=new Date();setters.y(now.getFullYear());setters.M((now.getMonth()+1).toFixed().padStart(2,'0'));setters.d(now.getDate().toFixed().padStart(2,'0'));if(set_12_24=='12'){let hour=now.getHours();hour=hour>12?hour-12:hour;setters.h(hour.toFixed().padStart(2,'0'));}else{setters.h(now.getHours().toFixed().padStart(2,'0'));}
setters.m(now.getMinutes().toFixed().padStart(2,'0'));const second=now.getSeconds();if(setters.s(second.toFixed().padStart(2,'0'))){const minAndSec=second+60*now.getMinutes();const day=(((now.getDate()-1)*86400+minAndSec+(3600*now.getHours()))/(new Date(now.getFullYear(),now.getMonth()+1,0).getDate()*86400))
timeMask.year.style.maxWidth=`${(now.getMonth() + day) / 0.12}%`;timeMask.month.style.maxWidth=`${day * 100}%`;timeMask.d.style.maxWidth=`${(minAndSec + 3600 * now.getHours()) / 864}%`;timeMask.h.style.maxWidth=`${minAndSec / 36}%`;timeMask.m.style.maxWidth=`${second / 0.6}%`;}};setInterval(updateText,1000);updateText();});win.wallpaperPropertyListener={applyUserProperties:function(properties){if(properties['date_size'])
doc.getElementById("date").style.fontSize=properties['date_size'].value+'px';if(properties['time_size'])
doc.getElementById("time").style.fontSize=properties['time_size'].value+'px';if(properties['header_slogan'])
doc.getElementById("header_slogan").innerText=properties['header_slogan'].value;if(properties['header_slogan_size'])
doc.getElementById("header_slogan").style.fontSize=properties['header_slogan_size'].value+'px';if(properties['footer_slogan'])
doc.getElementById("footer_slogan").innerText=properties['footer_slogan'].value;if(properties['footer_slogan_size'])
doc.getElementById("footer_slogan").style.fontSize=properties['footer_slogan_size'].value+'px';if(properties['min_color']){let customColor=properties['min_color'].value.split(' ');customColor=customColor.map(calculateColor);const backgroundColor="rgb("+customColor+")";doc.getElementsByClassName("m").item(0).style.borderColor=backgroundColor;doc.getElementsByClassName("m").item(0).getElementsByClassName('p').item(0).style.backgroundColor=backgroundColor;}
if(properties['hour_color']){let customColor=properties['hour_color'].value.split(' ');customColor=customColor.map(calculateColor);const backgroundColor="rgb("+customColor+")";doc.getElementsByClassName("h").item(0).style.borderColor=backgroundColor;doc.getElementsByClassName("h").item(0).getElementsByClassName('p').item(0).style.backgroundColor=backgroundColor;}
if(properties['month_color']){let customColor=properties['month_color'].value.split(' ');customColor=customColor.map(calculateColor);const backgroundColor="rgb("+customColor+")";doc.getElementsByClassName("month").item(0).style.borderColor=backgroundColor;doc.getElementsByClassName("month").item(0).getElementsByClassName('p').item(0).style.backgroundColor=backgroundColor;}
if(properties['year_color']){let customColor=properties['year_color'].value.split(' ');customColor=customColor.map(calculateColor);const backgroundColor="rgb("+customColor+")";doc.getElementsByClassName("year").item(0).style.borderColor=backgroundColor;doc.getElementsByClassName("year").item(0).getElementsByClassName('p').item(0).style.backgroundColor=backgroundColor;}
if(properties['day_color']){let customColor=properties['day_color'].value.split(' ');customColor=customColor.map(calculateColor);const backgroundColor="rgb("+customColor+")";doc.getElementsByClassName("d").item(0).style.borderColor=backgroundColor;doc.getElementsByClassName("d").item(0).getElementsByClassName('p').item(0).style.backgroundColor=backgroundColor;}
if(properties['text_color']){let customColor=properties['text_color'].value.split(' ');customColor=customColor.map(calculateColor);const color="rgb("+customColor+")";doc.getElementById("text").style.color=color;}
if(properties['background_image']){doc.getElementsByTagName("body").item(0).style.backgroundImage="url('"+"file:///"+properties['background_image'].value+"')";}
if(properties['position_h']){doc.getElementsByTagName("body").item(0).style.alignItems=properties['position_h'].value;}
if(properties['position_v']){doc.getElementsByTagName("body").item(0).style.justifyContent=properties['position_v'].value;}
if(properties['12_24']){set_12_24=properties['12_24'].value;}}}
function calculateColor(c){return Math.ceil(c*255);}})(document,window);